name: build-rules
on:
  workflow_dispatch:
  schedule:
    - cron: "00 19 * * *"

jobs:
  build-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize environment
        run: |
          echo "BUILDTIME=$(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M')" >> $GITHUB_ENV

      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: repo

      - name: Install sing-box
        run: |
          curl -fsSL https://sing-box.app/install.sh | sh

      - name: Rules json to binary
        run: |
          sing-box rule-set compile \
            --output repo/geosite/custom-cn.srs \
            repo/geosite/custom-cn.json

      - name: Commit and push changes
        run: |
          cd repo
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add geosite/custom-cn.srs
          git commit --allow-empty -m "released on ${{ env.BUILDTIME }}"
          git remote add new_origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u new_origin main
