name: build-rules
on:
  workflow_dispatch:
  schedule:
    - cron: "00 19 * * *"

jobs:
  build-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize environment
        run: |
          echo "BUILDTIME=$(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M')" >> $GITHUB_ENV

      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: repo

      - name: Download geolocation-!cn.json
        run: curl -o geolocation-!cn.json https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/sing/geo/geosite/geolocation-!cn.json

      - name: Download geoip-cn.json
        run: curl -o geoip-cn.json https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/sing/geo/geoip/cn.json

      - name: Mix rules
        run: |
          jq -n --slurpfile a geolocation-!cn.json --slurpfile b geoip-cn.json '{
            version: 2,
            rules: [{
              type: "logical",
              mode: "and",
              rules: [
                {
                  domain: $a[0].rules[0].domain,
                  domain_suffix: $a[0].rules[0].domain_suffix,
                  invert: true
                },
                {
                  ip_cidr: $b[0].rules[0].ip_cidr
                }
              ]
            }]
          }' > repo/geocn-mix.json

      - name: Install sing-box
        run: |
          curl -fsSL https://sing-box.app/install.sh | sh

      - name: Rules json to binary
        run: |
          sing-box rule-set compile \
            --output repo/geocn-mix.srs \
            repo/geocn-mix.json

      - name: Commit and push changes
        run: |
          cd repo
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add geosite/geocn-mix.json geosite/geocn-mix.srs
          git commit --allow-empty -m "released on ${{ env.BUILDTIME }}"
          git remote add new_origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u new_origin main
